/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Windows.Formularios;

/**
 *
 * @author RiosHenao
 */
public class EnterSelection extends javax.swing.JFrame {

    /**
     * Creates new form EnterSelection
     */
    boolean Iniciado;
    public EnterSelection() {
        initComponents();
        this.setLocationRelativeTo(null);
        LoginPanel.setVisible(false);
        RegisterPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        RegisterPanel = new javax.swing.JPanel();
        ComponentsRegisterPanel = new javax.swing.JPanel();
        PasswordTextInRegister = new javax.swing.JPasswordField();
        PasswordConfrimTextInResgister = new javax.swing.JPasswordField();
        UsernameTextInRegister = new javax.swing.JTextField();
        EmailTextInResgister = new javax.swing.JTextField();
        ReturnButtonInRegister = new javax.swing.JLabel();
        RegisterButtonInRegister = new javax.swing.JLabel();
        Background2 = new javax.swing.JLabel();
        LoginPanel = new javax.swing.JPanel();
        ComponentsLoginPanel = new javax.swing.JPanel();
        WindowControler = new javax.swing.JPanel();
        ExitButton1 = new javax.swing.JLabel();
        Maximizar = new javax.swing.JLabel();
        Minimizar = new javax.swing.JLabel();
        PasswordTextIntLogin = new javax.swing.JPasswordField();
        EmailTextInLogin = new javax.swing.JTextField();
        LoginButtonInLogin = new javax.swing.JLabel();
        ReturnButtonInLogin = new javax.swing.JLabel();
        Background1 = new javax.swing.JLabel();
        SelectionPanel = new javax.swing.JPanel();
        ComponentsSelectionPanel = new javax.swing.JPanel();
        ForgotButton = new javax.swing.JLabel();
        LoginButton = new javax.swing.JLabel();
        RegisterButton = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 500));
        setMinimumSize(new java.awt.Dimension(400, 500));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(400, 500));
        setResizable(false);

        RegisterPanel.setBackground(new java.awt.Color(0, 153, 102));
        RegisterPanel.setOpaque(false);
        RegisterPanel.setLayout(new java.awt.GridBagLayout());

        ComponentsRegisterPanel.setMaximumSize(new java.awt.Dimension(400, 500));
        ComponentsRegisterPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PasswordTextInRegister.setBackground(new java.awt.Color(255, 255, 255));
        PasswordTextInRegister.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        PasswordTextInRegister.setForeground(new java.awt.Color(20, 77, 95));
        PasswordTextInRegister.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PasswordTextInRegister.setBorder(null);
        PasswordTextInRegister.setCaretColor(new java.awt.Color(20, 77, 95));
        PasswordTextInRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTextInRegisterActionPerformed(evt);
            }
        });
        ComponentsRegisterPanel.add(PasswordTextInRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 280, 40));

        PasswordConfrimTextInResgister.setBackground(new java.awt.Color(255, 255, 255));
        PasswordConfrimTextInResgister.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        PasswordConfrimTextInResgister.setForeground(new java.awt.Color(20, 77, 95));
        PasswordConfrimTextInResgister.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PasswordConfrimTextInResgister.setBorder(null);
        PasswordConfrimTextInResgister.setCaretColor(new java.awt.Color(20, 77, 95));
        PasswordConfrimTextInResgister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordConfrimTextInResgisterActionPerformed(evt);
            }
        });
        ComponentsRegisterPanel.add(PasswordConfrimTextInResgister, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 280, 40));

        UsernameTextInRegister.setBackground(new java.awt.Color(255, 255, 255));
        UsernameTextInRegister.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UsernameTextInRegister.setForeground(new java.awt.Color(20, 77, 95));
        UsernameTextInRegister.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        UsernameTextInRegister.setBorder(null);
        UsernameTextInRegister.setCaretColor(new java.awt.Color(20, 77, 95));
        UsernameTextInRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTextInRegisterActionPerformed(evt);
            }
        });
        ComponentsRegisterPanel.add(UsernameTextInRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 280, 40));

        EmailTextInResgister.setBackground(new java.awt.Color(255, 255, 255));
        EmailTextInResgister.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EmailTextInResgister.setForeground(new java.awt.Color(20, 77, 95));
        EmailTextInResgister.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EmailTextInResgister.setBorder(null);
        EmailTextInResgister.setCaretColor(new java.awt.Color(20, 77, 95));
        EmailTextInResgister.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                EmailTextInResgisterPropertyChange(evt);
            }
        });
        ComponentsRegisterPanel.add(EmailTextInResgister, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 280, 40));

        ReturnButtonInRegister.setFont(new java.awt.Font("Dubai Light", 1, 36)); // NOI18N
        ReturnButtonInRegister.setForeground(new java.awt.Color(255, 255, 255));
        ReturnButtonInRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ReturnButtonInRegister.setText("X");
        ReturnButtonInRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReturnButtonInRegisterMouseClicked(evt);
            }
        });
        ComponentsRegisterPanel.add(ReturnButtonInRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        RegisterButtonInRegister.setBackground(new java.awt.Color(113, 177, 128));
        RegisterButtonInRegister.setFont(new java.awt.Font("Dubai Light", 0, 24)); // NOI18N
        RegisterButtonInRegister.setForeground(new java.awt.Color(255, 255, 255));
        RegisterButtonInRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegisterButtonInRegister.setText("REGISTER");
        RegisterButtonInRegister.setOpaque(true);
        ComponentsRegisterPanel.add(RegisterButtonInRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 200, -1));

        Background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/MenuSelector.png"))); // NOI18N
        Background2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Background2MouseDragged(evt);
            }
        });
        Background2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Background2MousePressed(evt);
            }
        });
        ComponentsRegisterPanel.add(Background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 500));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 400.0;
        gridBagConstraints.weighty = 500.0;
        RegisterPanel.add(ComponentsRegisterPanel, gridBagConstraints);

        LoginPanel.setBackground(new java.awt.Color(0, 153, 102));
        LoginPanel.setOpaque(false);
        LoginPanel.setLayout(new java.awt.GridBagLayout());

        ComponentsLoginPanel.setMaximumSize(new java.awt.Dimension(400, 500));
        ComponentsLoginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WindowControler.setOpaque(false);

        ExitButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ExitButton1.setForeground(new java.awt.Color(255, 255, 255));
        ExitButton1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ExitButton1.setText("X");
        ExitButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitButton1MouseClicked(evt);
            }
        });

        Maximizar.setBackground(new java.awt.Color(30, 30, 30));
        Maximizar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Maximizar.setForeground(new java.awt.Color(255, 255, 255));
        Maximizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Maximizar.setText("▭");
        Maximizar.setAlignmentY(0.0F);
        Maximizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MaximizarMouseClicked(evt);
            }
        });

        Minimizar.setBackground(new java.awt.Color(30, 30, 30));
        Minimizar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Minimizar.setForeground(new java.awt.Color(255, 255, 255));
        Minimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Minimizar.setText("—");
        Minimizar.setAlignmentY(0.0F);
        Minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout WindowControlerLayout = new javax.swing.GroupLayout(WindowControler);
        WindowControler.setLayout(WindowControlerLayout);
        WindowControlerLayout.setHorizontalGroup(
            WindowControlerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(WindowControlerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(WindowControlerLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(Maximizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(ExitButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        WindowControlerLayout.setVerticalGroup(
            WindowControlerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(WindowControlerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(WindowControlerLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(WindowControlerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Maximizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ExitButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        ComponentsLoginPanel.add(WindowControler, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 100, 40));

        PasswordTextIntLogin.setBackground(new java.awt.Color(255, 255, 255));
        PasswordTextIntLogin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        PasswordTextIntLogin.setForeground(new java.awt.Color(20, 77, 95));
        PasswordTextIntLogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PasswordTextIntLogin.setBorder(null);
        PasswordTextIntLogin.setCaretColor(new java.awt.Color(20, 77, 95));
        PasswordTextIntLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTextIntLoginActionPerformed(evt);
            }
        });
        ComponentsLoginPanel.add(PasswordTextIntLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 280, 40));

        EmailTextInLogin.setBackground(new java.awt.Color(255, 255, 255));
        EmailTextInLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EmailTextInLogin.setForeground(new java.awt.Color(20, 77, 95));
        EmailTextInLogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EmailTextInLogin.setBorder(null);
        EmailTextInLogin.setCaretColor(new java.awt.Color(20, 77, 95));
        EmailTextInLogin.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                EmailTextInLoginPropertyChange(evt);
            }
        });
        ComponentsLoginPanel.add(EmailTextInLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 280, 40));

        LoginButtonInLogin.setBackground(new java.awt.Color(113, 177, 128));
        LoginButtonInLogin.setFont(new java.awt.Font("Dubai Light", 0, 24)); // NOI18N
        LoginButtonInLogin.setForeground(new java.awt.Color(255, 255, 255));
        LoginButtonInLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginButtonInLogin.setText("LOGIN");
        LoginButtonInLogin.setOpaque(true);
        LoginButtonInLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginButtonInLoginMouseClicked(evt);
            }
        });
        ComponentsLoginPanel.add(LoginButtonInLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 190, -1));

        ReturnButtonInLogin.setFont(new java.awt.Font("Dubai Light", 1, 36)); // NOI18N
        ReturnButtonInLogin.setForeground(new java.awt.Color(255, 255, 255));
        ReturnButtonInLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ReturnButtonInLogin.setText("X");
        ReturnButtonInLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReturnButtonInLoginMouseClicked(evt);
            }
        });
        ComponentsLoginPanel.add(ReturnButtonInLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        Background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/MenuSelector.png"))); // NOI18N
        Background1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Background1MouseDragged(evt);
            }
        });
        Background1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Background1MousePressed(evt);
            }
        });
        ComponentsLoginPanel.add(Background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 500));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 400.0;
        gridBagConstraints.weighty = 500.0;
        LoginPanel.add(ComponentsLoginPanel, gridBagConstraints);

        SelectionPanel.setBackground(new java.awt.Color(0, 153, 102));
        SelectionPanel.setOpaque(false);
        SelectionPanel.setLayout(new java.awt.GridBagLayout());

        ComponentsSelectionPanel.setMaximumSize(new java.awt.Dimension(400, 500));
        ComponentsSelectionPanel.setMinimumSize(new java.awt.Dimension(400, 500));
        ComponentsSelectionPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ForgotButton.setForeground(new java.awt.Color(255, 255, 255));
        ForgotButton.setText("Forgot your account?");
        ComponentsSelectionPanel.add(ForgotButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, -1, -1));

        LoginButton.setBackground(new java.awt.Color(113, 177, 128));
        LoginButton.setFont(new java.awt.Font("Dubai Light", 0, 24)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(255, 255, 255));
        LoginButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginButton.setText("LOGIN");
        LoginButton.setOpaque(true);
        LoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginButtonMouseClicked(evt);
            }
        });
        ComponentsSelectionPanel.add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 190, -1));

        RegisterButton.setBackground(new java.awt.Color(113, 177, 128));
        RegisterButton.setFont(new java.awt.Font("Dubai Light", 0, 24)); // NOI18N
        RegisterButton.setForeground(new java.awt.Color(255, 255, 255));
        RegisterButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegisterButton.setText("REGISTER");
        RegisterButton.setOpaque(true);
        RegisterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterButtonMouseClicked(evt);
            }
        });
        ComponentsSelectionPanel.add(RegisterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 190, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/MenuSelector.png"))); // NOI18N
        Background.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BackgroundMouseDragged(evt);
            }
        });
        Background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BackgroundMousePressed(evt);
            }
        });
        ComponentsSelectionPanel.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 400.0;
        gridBagConstraints.weighty = 500.0;
        SelectionPanel.add(ComponentsSelectionPanel, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SelectionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(LoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(RegisterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SelectionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(LoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(RegisterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackgroundMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackgroundMouseDragged
        // TODO add your handling code here:
        if (this.getBounds().getWidth()<410){
            int x = evt.getXOnScreen();
            int y = evt.getYOnScreen();
            this.setLocation(x-xx,y-xy);
        }
    }//GEN-LAST:event_BackgroundMouseDragged
    int xx,xy;
    private void BackgroundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackgroundMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_BackgroundMousePressed
    private int xOnScreen;
    private int yOnScreen;
    private void LoginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseClicked
        // TODO add your handling code here:
        LoginPanel.setVisible(true);
        System.out.println("Login mostrado");
        RegisterPanel.setVisible(false);
        this.setVisible(false);
        /*int x = this.getLocationOnScreen().x;
        int y = this.getLocationOnScreen().y;
        
        Windows.Formularios.LoginForm Login = new Windows.Formularios.LoginForm();
        setXOnScreen(x);
        setYOnScreen(y);
        Login.setLocationRelativeToSelector(getXOnScreen(), getYOnScreen());
        Login.setVisible(true);
        this.setVisible(false);*/
    }//GEN-LAST:event_LoginButtonMouseClicked

    private void RegisterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterButtonMouseClicked
        // TODO add your handling code here:
        int x = this.getLocationOnScreen().x;
        int y = this.getLocationOnScreen().y;
        
        Windows.Formularios.RegisterForm Register = new Windows.Formularios.RegisterForm();
        setXOnScreen(x);
        setYOnScreen(y);
        Register.setLocationRelativeToSelector(getXOnScreen(), getYOnScreen());
        Register.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_RegisterButtonMouseClicked
    private int xMinimized = 0;
    private int yMinimized = 0;
    private int StateForm = 0;

    public int getStateForm() {
        return StateForm;
    }

    public void setStateForm(int State) {
        this.StateForm = State;
    }


    public int getxMinimized() {
        return xMinimized;
    }

    public void setxMinimized(int xMinimized) {
        this.xMinimized = xMinimized;
    }

    public int getyMinimized() {
        return yMinimized;
    }

    public void setyMinimized(int yMinimized) {
        this.yMinimized = yMinimized;
    }
    private void ExitButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButton1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitButton1MouseClicked

    private void MaximizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaximizarMouseClicked
        // TODO add your handling code here:

        if (this.getExtendedState() == MAXIMIZED_BOTH){
            this.setExtendedState(NORMAL);
            this.setBounds(getxMinimized(), getyMinimized(), 400, 500);
        }else{
            setxMinimized(this.getLocationOnScreen().x);
            setyMinimized(this.getLocationOnScreen().y);
            this.setExtendedState(MAXIMIZED_BOTH);

        }
    }//GEN-LAST:event_MaximizarMouseClicked

    private void MinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarMouseClicked
        setStateForm(this.getExtendedState());
        this.setExtendedState(1);
    }//GEN-LAST:event_MinimizarMouseClicked

    private void PasswordTextIntLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTextIntLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTextIntLoginActionPerformed

    private void EmailTextInLoginPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_EmailTextInLoginPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailTextInLoginPropertyChange

    private void LoginButtonInLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonInLoginMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginButtonInLoginMouseClicked

    private void ReturnButtonInLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReturnButtonInLoginMouseClicked
        // TODO add your handling code here:
        int x = this.getLocationOnScreen().x;
        int y = this.getLocationOnScreen().y;
        setXOnScreen(x);
        setYOnScreen(y);
        Windows.Formularios.EnterSelection Selection = new Windows.Formularios.EnterSelection();
        Selection.setLocationRelativeToRegisterLogin(getXOnScreen(), getYOnScreen());
        Selection.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ReturnButtonInLoginMouseClicked

    private void Background1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Background1MouseDragged
        // TODO add your handling code here:

        if (this.getBounds().getWidth()<410){
            int x = evt.getXOnScreen();
            int y = evt.getYOnScreen();
            this.setLocation(x-xx,y-xy);
        }
    }//GEN-LAST:event_Background1MouseDragged

    private void Background1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Background1MousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_Background1MousePressed

    private void PasswordTextInRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTextInRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTextInRegisterActionPerformed

    private void PasswordConfrimTextInResgisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordConfrimTextInResgisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordConfrimTextInResgisterActionPerformed

    private void UsernameTextInRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTextInRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameTextInRegisterActionPerformed

    private void EmailTextInResgisterPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_EmailTextInResgisterPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailTextInResgisterPropertyChange

    private void ReturnButtonInRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReturnButtonInRegisterMouseClicked
        // TODO add your handling code here:
        int x = this.getLocationOnScreen().x;
        int y = this.getLocationOnScreen().y;
        setXOnScreen(x);
        setYOnScreen(y);
        Windows.Formularios.EnterSelection Selection = new Windows.Formularios.EnterSelection();
        Selection.setLocationRelativeToRegisterLogin(getXOnScreen(), getYOnScreen());
        Selection.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ReturnButtonInRegisterMouseClicked

    private void Background2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Background2MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_Background2MouseDragged

    private void Background2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Background2MousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_Background2MousePressed
    
    public void setLocationRelativeToRegisterLogin(int x, int y){
        this.setBounds(x,y,400,500);
    }
    public void setXOnScreen(int xOnScreen){
        this.xOnScreen = xOnScreen;
    } 
    
    public void setYOnScreen(int yOnScreen){
        this.yOnScreen = yOnScreen;
    }
    
    public int getXOnScreen(){
        return xOnScreen;
    }
    
    public int getYOnScreen(){
        return yOnScreen;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnterSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnterSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnterSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnterSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnterSelection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Background1;
    private javax.swing.JLabel Background2;
    private javax.swing.JPanel ComponentsLoginPanel;
    private javax.swing.JPanel ComponentsRegisterPanel;
    private javax.swing.JPanel ComponentsSelectionPanel;
    private javax.swing.JTextField EmailTextInLogin;
    private javax.swing.JTextField EmailTextInResgister;
    private javax.swing.JLabel ExitButton1;
    private javax.swing.JLabel ForgotButton;
    private javax.swing.JLabel LoginButton;
    private javax.swing.JLabel LoginButtonInLogin;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JLabel Maximizar;
    private javax.swing.JLabel Minimizar;
    private javax.swing.JPasswordField PasswordConfrimTextInResgister;
    private javax.swing.JPasswordField PasswordTextInRegister;
    private javax.swing.JPasswordField PasswordTextIntLogin;
    private javax.swing.JLabel RegisterButton;
    private javax.swing.JLabel RegisterButtonInRegister;
    private javax.swing.JPanel RegisterPanel;
    private javax.swing.JLabel ReturnButtonInLogin;
    private javax.swing.JLabel ReturnButtonInRegister;
    private javax.swing.JPanel SelectionPanel;
    private javax.swing.JTextField UsernameTextInRegister;
    private javax.swing.JPanel WindowControler;
    // End of variables declaration//GEN-END:variables
}
