/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Windows.Formularios;

import javax.swing.ImageIcon;


/**
 *
 * @author RiosHenao
 */
public class EnterSelection extends javax.swing.JFrame {

    /**
     * Creates new form EnterSelection
     */
    boolean Iniciado;
    public EnterSelection() {
        initComponents();
        this.setLocationRelativeTo(null);
        LoginPanel.setVisible(false);
        RegisterPanel.setVisible(false);
        ReturnButtonInLogin.setIcon(new ImageIcon(new ImageIcon(getClass().getResource("/Resources/Volver.png")).getImage().getScaledInstance((ReturnButtonInLogin.getWidth()-1),(ReturnButtonInLogin.getHeight()-1),java.awt.Image.SCALE_SMOOTH)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PanelContenedor = new javax.swing.JPanel();
        WindowControler = new javax.swing.JPanel();
        ExitButton1 = new javax.swing.JLabel();
        Maximizar = new javax.swing.JLabel();
        Minimizar = new javax.swing.JLabel();
        SelectionPanel = new javax.swing.JPanel();
        ComponentsSelectionPanel = new javax.swing.JPanel();
        ForgotButton = new javax.swing.JLabel();
        LoginButton = new javax.swing.JLabel();
        RegisterButton = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();
        LoginPanel = new javax.swing.JPanel();
        ComponentsLoginPanel = new javax.swing.JPanel();
        PasswordTextIntLogin = new javax.swing.JPasswordField();
        EmailTextInLogin = new javax.swing.JTextField();
        LoginButtonInLogin = new javax.swing.JLabel();
        ReturnButtonInLogin = new javax.swing.JLabel();
        Background1 = new javax.swing.JLabel();
        RegisterPanel = new javax.swing.JPanel();
        ComponentsRegisterPanel = new javax.swing.JPanel();
        PasswordTextInRegister = new javax.swing.JPasswordField();
        PasswordConfrimTextInResgister = new javax.swing.JPasswordField();
        UsernameTextInRegister = new javax.swing.JTextField();
        EmailTextInResgister = new javax.swing.JTextField();
        ReturnButtonInRegister = new javax.swing.JLabel();
        RegisterButtonInRegister = new javax.swing.JLabel();
        Background2 = new javax.swing.JLabel();
        BackGroundResponsive = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 500));
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        PanelContenedor.setBackground(new java.awt.Color(0, 153, 102));
        PanelContenedor.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        PanelContenedor.setMinimumSize(new java.awt.Dimension(400, 500));
        PanelContenedor.setOpaque(false);
        PanelContenedor.setPreferredSize(new java.awt.Dimension(400, 500));
        PanelContenedor.setLayout(new java.awt.GridBagLayout());

        WindowControler.setOpaque(false);
        WindowControler.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ExitButton1.setBackground(new java.awt.Color(76, 137, 115));
        ExitButton1.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        ExitButton1.setForeground(new java.awt.Color(255, 255, 255));
        ExitButton1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ExitButton1.setText("X");
        ExitButton1.setOpaque(true);
        ExitButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitButton1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ExitButton1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ExitButton1MouseReleased(evt);
            }
        });
        WindowControler.add(ExitButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 40, 40));

        Maximizar.setBackground(new java.awt.Color(79, 140, 116));
        Maximizar.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        Maximizar.setForeground(new java.awt.Color(255, 255, 255));
        Maximizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Maximizar.setText("▭");
        Maximizar.setAlignmentY(0.0F);
        Maximizar.setOpaque(true);
        Maximizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MaximizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MaximizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MaximizarMouseExited(evt);
            }
        });
        WindowControler.add(Maximizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 40, 40));

        Minimizar.setBackground(new java.awt.Color(82, 144, 117));
        Minimizar.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        Minimizar.setForeground(new java.awt.Color(255, 255, 255));
        Minimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Minimizar.setText("—");
        Minimizar.setAlignmentY(0.0F);
        Minimizar.setOpaque(true);
        Minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MinimizarMouseExited(evt);
            }
        });
        WindowControler.add(Minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 280, 0, 0);
        PanelContenedor.add(WindowControler, gridBagConstraints);

        SelectionPanel.setBackground(new java.awt.Color(0, 153, 102));
        SelectionPanel.setOpaque(false);
        SelectionPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ComponentsSelectionPanel.setMaximumSize(new java.awt.Dimension(400, 500));
        ComponentsSelectionPanel.setMinimumSize(new java.awt.Dimension(400, 500));
        ComponentsSelectionPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ForgotButton.setForeground(new java.awt.Color(255, 255, 255));
        ForgotButton.setText("Forgot your account?");
        ComponentsSelectionPanel.add(ForgotButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, -1, -1));

        LoginButton.setBackground(new java.awt.Color(113, 177, 128));
        LoginButton.setFont(new java.awt.Font("Dubai Light", 0, 24)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(255, 255, 255));
        LoginButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginButton.setText("LOGIN");
        LoginButton.setOpaque(true);
        LoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginButtonMouseExited(evt);
            }
        });
        ComponentsSelectionPanel.add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 190, -1));

        RegisterButton.setBackground(new java.awt.Color(113, 177, 128));
        RegisterButton.setFont(new java.awt.Font("Dubai Light", 0, 24)); // NOI18N
        RegisterButton.setForeground(new java.awt.Color(255, 255, 255));
        RegisterButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegisterButton.setText("REGISTER");
        RegisterButton.setOpaque(true);
        RegisterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegisterButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegisterButtonMouseExited(evt);
            }
        });
        ComponentsSelectionPanel.add(RegisterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 190, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/MenuSelector.png"))); // NOI18N
        Background.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BackgroundMouseDragged(evt);
            }
        });
        Background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BackgroundMousePressed(evt);
            }
        });
        ComponentsSelectionPanel.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        SelectionPanel.add(ComponentsSelectionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        PanelContenedor.add(SelectionPanel, gridBagConstraints);

        LoginPanel.setBackground(new java.awt.Color(0, 153, 102));
        LoginPanel.setOpaque(false);
        LoginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ComponentsLoginPanel.setMaximumSize(new java.awt.Dimension(400, 500));
        ComponentsLoginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PasswordTextIntLogin.setBackground(new java.awt.Color(255, 255, 255));
        PasswordTextIntLogin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        PasswordTextIntLogin.setForeground(new java.awt.Color(20, 77, 95));
        PasswordTextIntLogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PasswordTextIntLogin.setBorder(null);
        PasswordTextIntLogin.setCaretColor(new java.awt.Color(20, 77, 95));
        PasswordTextIntLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTextIntLoginActionPerformed(evt);
            }
        });
        ComponentsLoginPanel.add(PasswordTextIntLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 280, 40));

        EmailTextInLogin.setBackground(new java.awt.Color(255, 255, 255));
        EmailTextInLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EmailTextInLogin.setForeground(new java.awt.Color(20, 77, 95));
        EmailTextInLogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EmailTextInLogin.setBorder(null);
        EmailTextInLogin.setCaretColor(new java.awt.Color(20, 77, 95));
        EmailTextInLogin.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                EmailTextInLoginPropertyChange(evt);
            }
        });
        ComponentsLoginPanel.add(EmailTextInLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 280, 40));

        LoginButtonInLogin.setBackground(new java.awt.Color(113, 177, 128));
        LoginButtonInLogin.setFont(new java.awt.Font("Dubai Light", 0, 24)); // NOI18N
        LoginButtonInLogin.setForeground(new java.awt.Color(255, 255, 255));
        LoginButtonInLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginButtonInLogin.setText("LOGIN");
        LoginButtonInLogin.setOpaque(true);
        LoginButtonInLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginButtonInLoginMouseClicked(evt);
            }
        });
        ComponentsLoginPanel.add(LoginButtonInLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 190, -1));

        ReturnButtonInLogin.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        ReturnButtonInLogin.setForeground(new java.awt.Color(255, 255, 255));
        ReturnButtonInLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ReturnButtonInLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Volver.png"))); // NOI18N
        ReturnButtonInLogin.setMaximumSize(new java.awt.Dimension(23, 31));
        ReturnButtonInLogin.setMinimumSize(new java.awt.Dimension(23, 31));
        ReturnButtonInLogin.setPreferredSize(new java.awt.Dimension(23, 31));
        ReturnButtonInLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReturnButtonInLoginMouseClicked(evt);
            }
        });
        ComponentsLoginPanel.add(ReturnButtonInLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        Background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/MenuSelector.png"))); // NOI18N
        Background1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Background1MouseDragged(evt);
            }
        });
        Background1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Background1MousePressed(evt);
            }
        });
        ComponentsLoginPanel.add(Background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 500));

        LoginPanel.add(ComponentsLoginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        PanelContenedor.add(LoginPanel, gridBagConstraints);

        RegisterPanel.setBackground(new java.awt.Color(0, 153, 102));
        RegisterPanel.setOpaque(false);
        RegisterPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ComponentsRegisterPanel.setMaximumSize(new java.awt.Dimension(400, 500));
        ComponentsRegisterPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PasswordTextInRegister.setBackground(new java.awt.Color(255, 255, 255));
        PasswordTextInRegister.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        PasswordTextInRegister.setForeground(new java.awt.Color(20, 77, 95));
        PasswordTextInRegister.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PasswordTextInRegister.setBorder(null);
        PasswordTextInRegister.setCaretColor(new java.awt.Color(20, 77, 95));
        PasswordTextInRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTextInRegisterActionPerformed(evt);
            }
        });
        ComponentsRegisterPanel.add(PasswordTextInRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 280, 40));

        PasswordConfrimTextInResgister.setBackground(new java.awt.Color(255, 255, 255));
        PasswordConfrimTextInResgister.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        PasswordConfrimTextInResgister.setForeground(new java.awt.Color(20, 77, 95));
        PasswordConfrimTextInResgister.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PasswordConfrimTextInResgister.setBorder(null);
        PasswordConfrimTextInResgister.setCaretColor(new java.awt.Color(20, 77, 95));
        PasswordConfrimTextInResgister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordConfrimTextInResgisterActionPerformed(evt);
            }
        });
        ComponentsRegisterPanel.add(PasswordConfrimTextInResgister, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 280, 40));

        UsernameTextInRegister.setBackground(new java.awt.Color(255, 255, 255));
        UsernameTextInRegister.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UsernameTextInRegister.setForeground(new java.awt.Color(20, 77, 95));
        UsernameTextInRegister.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        UsernameTextInRegister.setBorder(null);
        UsernameTextInRegister.setCaretColor(new java.awt.Color(20, 77, 95));
        UsernameTextInRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTextInRegisterActionPerformed(evt);
            }
        });
        ComponentsRegisterPanel.add(UsernameTextInRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 280, 40));

        EmailTextInResgister.setBackground(new java.awt.Color(255, 255, 255));
        EmailTextInResgister.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EmailTextInResgister.setForeground(new java.awt.Color(20, 77, 95));
        EmailTextInResgister.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EmailTextInResgister.setBorder(null);
        EmailTextInResgister.setCaretColor(new java.awt.Color(20, 77, 95));
        EmailTextInResgister.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                EmailTextInResgisterPropertyChange(evt);
            }
        });
        ComponentsRegisterPanel.add(EmailTextInResgister, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 280, 40));

        ReturnButtonInRegister.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        ReturnButtonInRegister.setForeground(new java.awt.Color(255, 255, 255));
        ReturnButtonInRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ReturnButtonInRegister.setText("<");
        ReturnButtonInRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReturnButtonInRegisterMouseClicked(evt);
            }
        });
        ComponentsRegisterPanel.add(ReturnButtonInRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        RegisterButtonInRegister.setBackground(new java.awt.Color(113, 177, 128));
        RegisterButtonInRegister.setFont(new java.awt.Font("Dubai Light", 0, 24)); // NOI18N
        RegisterButtonInRegister.setForeground(new java.awt.Color(255, 255, 255));
        RegisterButtonInRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegisterButtonInRegister.setText("REGISTER");
        RegisterButtonInRegister.setOpaque(true);
        ComponentsRegisterPanel.add(RegisterButtonInRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 200, -1));

        Background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/MenuSelector.png"))); // NOI18N
        Background2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Background2MouseDragged(evt);
            }
        });
        Background2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Background2MousePressed(evt);
            }
        });
        ComponentsRegisterPanel.add(Background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 500));

        RegisterPanel.add(ComponentsRegisterPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        PanelContenedor.add(RegisterPanel, gridBagConstraints);

        BackGroundResponsive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Gradient.png"))); // NOI18N
        BackGroundResponsive.setMinimumSize(new java.awt.Dimension(400, 500));
        BackGroundResponsive.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackGroundResponsiveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(BackGroundResponsive, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(BackGroundResponsive, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackgroundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackgroundMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_BackgroundMousePressed

    private void BackgroundMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackgroundMouseDragged
        // TODO add your handling code here:
        if (this.getBounds().getWidth()<410){
            int x = evt.getXOnScreen();
            int y = evt.getYOnScreen();
            this.setLocation(x-xx,y-xy);
        }
    }//GEN-LAST:event_BackgroundMouseDragged

    private void RegisterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterButtonMouseClicked
        // TODO add your handling code here:
        LoginPanel.setVisible(false);
        RegisterPanel.setVisible(true);
        SelectionPanel.setVisible(false);
        System.out.println("Register mostrado");
    }//GEN-LAST:event_RegisterButtonMouseClicked

    private void LoginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseClicked
        // TODO add your handling code here:
        LoginPanel.setVisible(true);
        RegisterPanel.setVisible(false);
        SelectionPanel.setVisible(false);
        System.out.println("Login mostrado");
    }//GEN-LAST:event_LoginButtonMouseClicked

    private void Background2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Background2MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_Background2MousePressed

    private void Background2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Background2MouseDragged
        if (this.getBounds().getWidth()<410){
            int x = evt.getXOnScreen();
            int y = evt.getYOnScreen();
            this.setLocation(x-xx,y-xy);
        }
    }//GEN-LAST:event_Background2MouseDragged

    private void ReturnButtonInRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReturnButtonInRegisterMouseClicked
        SelectionPanel.setVisible(true);
        LoginPanel.setVisible(false);
        RegisterPanel.setVisible(false);
        System.out.println("Selectot mostrado");
    }//GEN-LAST:event_ReturnButtonInRegisterMouseClicked

    private void EmailTextInResgisterPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_EmailTextInResgisterPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailTextInResgisterPropertyChange

    private void UsernameTextInRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTextInRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameTextInRegisterActionPerformed

    private void PasswordConfrimTextInResgisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordConfrimTextInResgisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordConfrimTextInResgisterActionPerformed

    private void PasswordTextInRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTextInRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTextInRegisterActionPerformed

    private void Background1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Background1MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_Background1MousePressed

    private void Background1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Background1MouseDragged
        if (this.getBounds().getWidth()<=400){
            int x = evt.getXOnScreen();
            int y = evt.getYOnScreen();
            this.setLocation(x-xx,y-xy);
        }
    }//GEN-LAST:event_Background1MouseDragged

    private void ReturnButtonInLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReturnButtonInLoginMouseClicked
        SelectionPanel.setVisible(true);
        LoginPanel.setVisible(false);
        RegisterPanel.setVisible(false);
        System.out.println("Selectot mostrado");
    }//GEN-LAST:event_ReturnButtonInLoginMouseClicked

    private void LoginButtonInLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonInLoginMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginButtonInLoginMouseClicked

    private void EmailTextInLoginPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_EmailTextInLoginPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailTextInLoginPropertyChange

    private void PasswordTextIntLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTextIntLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTextIntLoginActionPerformed

    private void MinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarMouseClicked
        setStateForm(this.getExtendedState());
        this.setExtendedState(1);
    }//GEN-LAST:event_MinimizarMouseClicked

    private void MaximizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaximizarMouseClicked
        if (this.getExtendedState() == MAXIMIZED_BOTH){
            this.setExtendedState(NORMAL);
            this.setBounds(getxMinimized(), getyMinimized(), 400, 500);
        }else{
            setxMinimized(this.getLocationOnScreen().x);
            setyMinimized(this.getLocationOnScreen().y);
            this.setExtendedState(MAXIMIZED_BOTH);

        }
    }//GEN-LAST:event_MaximizarMouseClicked

    private void ExitButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButton1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitButton1MouseClicked

    private void BackGroundResponsiveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackGroundResponsiveMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BackGroundResponsiveMouseClicked

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        this.setExtendedState(getStateForm());
    }//GEN-LAST:event_formWindowGainedFocus

    private void ExitButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButton1MouseEntered
        ExitButton1.setBackground(new java.awt.Color(255,137,115));
    }//GEN-LAST:event_ExitButton1MouseEntered

    private void ExitButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButton1MouseExited
        ExitButton1.setBackground(new java.awt.Color(76,137,115));
    }//GEN-LAST:event_ExitButton1MouseExited

    private void MaximizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaximizarMouseEntered
        Maximizar.setBackground(new java.awt.Color(132,193,147));
    }//GEN-LAST:event_MaximizarMouseEntered

    private void MaximizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaximizarMouseExited
        Maximizar.setBackground(new java.awt.Color(79,140,116));
    }//GEN-LAST:event_MaximizarMouseExited

    private void MinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarMouseEntered
        Minimizar.setBackground(new java.awt.Color(132,193,147));
    }//GEN-LAST:event_MinimizarMouseEntered

    private void MinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarMouseExited
        Minimizar.setBackground(new java.awt.Color(82,144,117));
    }//GEN-LAST:event_MinimizarMouseExited

    private void ExitButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButton1MousePressed
        //
    }//GEN-LAST:event_ExitButton1MousePressed

    private void ExitButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButton1MouseReleased
        //
    }//GEN-LAST:event_ExitButton1MouseReleased

    private void LoginButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseExited
        // TODO add your handling code here:
        LoginButton.setBackground(new java.awt.Color(113,177,128));
    }//GEN-LAST:event_LoginButtonMouseExited

    private void RegisterButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterButtonMouseExited
        // TODO add your handling code here:
        RegisterButton.setBackground(new java.awt.Color(113,177,128));
    }//GEN-LAST:event_RegisterButtonMouseExited

    private void LoginButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseEntered
        LoginButton.setBackground(new java.awt.Color(132,193,147));
    }//GEN-LAST:event_LoginButtonMouseEntered

    private void RegisterButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterButtonMouseEntered
        RegisterButton.setBackground(new java.awt.Color(132,193,147));
    }//GEN-LAST:event_RegisterButtonMouseEntered
    int xx,xy;    
  
    private int xMinimized = 0;
    private int yMinimized = 0;
    private int StateForm = 0;

    public int getStateForm() {
        return StateForm;
    }
    public void setStateForm(int State) {
        this.StateForm = State;
    }
    public int getxMinimized() {
        return xMinimized;
    }
    public void setxMinimized(int xMinimized) {
        this.xMinimized = xMinimized;
    }
    public int getyMinimized() {
        return yMinimized;
    }
    public void setyMinimized(int yMinimized) {
        this.yMinimized = yMinimized;
    }    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnterSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnterSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnterSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnterSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnterSelection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel BackGroundResponsive;
    public javax.swing.JLabel Background;
    public javax.swing.JLabel Background1;
    public javax.swing.JLabel Background2;
    public javax.swing.JPanel ComponentsLoginPanel;
    public javax.swing.JPanel ComponentsRegisterPanel;
    public javax.swing.JPanel ComponentsSelectionPanel;
    public javax.swing.JTextField EmailTextInLogin;
    public javax.swing.JTextField EmailTextInResgister;
    public javax.swing.JLabel ExitButton1;
    public javax.swing.JLabel ForgotButton;
    public javax.swing.JLabel LoginButton;
    public javax.swing.JLabel LoginButtonInLogin;
    public javax.swing.JPanel LoginPanel;
    public javax.swing.JLabel Maximizar;
    public javax.swing.JLabel Minimizar;
    public javax.swing.JPanel PanelContenedor;
    public javax.swing.JPasswordField PasswordConfrimTextInResgister;
    public javax.swing.JPasswordField PasswordTextInRegister;
    public javax.swing.JPasswordField PasswordTextIntLogin;
    public javax.swing.JLabel RegisterButton;
    public javax.swing.JLabel RegisterButtonInRegister;
    public javax.swing.JPanel RegisterPanel;
    public javax.swing.JLabel ReturnButtonInLogin;
    public javax.swing.JLabel ReturnButtonInRegister;
    public javax.swing.JPanel SelectionPanel;
    public javax.swing.JTextField UsernameTextInRegister;
    public javax.swing.JPanel WindowControler;
    // End of variables declaration//GEN-END:variables
}
